### ISSUE TITLE
launch failed: with fix

### ISSUE THREAD

**Issue by sgwood63** [learnk8s/learnk8s.io#118]
bundle exec jekyll server -H 0.0.0.0 --incremental

root@a7f3fe851bb1:/app# bundle exec jekyll server -H 0.0.0.0 --incremental
Configuration file: /app/_config.yml
            Source: /app
       Destination: /app/_site
 Incremental build: enabled
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/style.scss':
                    File to import not found or unreadable: tachyons-sass/tachyons.scss. on line 1
jekyll 3.7.3 | Error:  File to import not found or unreadable: tachyons-sass/tachyons.scss. on line 1

Fix

npm install --save tachyons-sass

**Comment by keithmifsud** [comment]
I think this issue can be closed now. Also, I think that all node packages should be installed not just tachyons. `npm install --save`?

**Comment by sgwood63** [comment]
The real fix would be to ensure tachyons-sass is installed when you do the "bundle install".

**Comment by danielepolencic** [comment]
This is not applicable anymore. Closing.
