### ISSUE TITLE
Investigate RSS feed

### ISSUE THREAD

**Issue by danielepolencic** [learnk8s/learnk8s.io#131]
Readers expressed the interest in subscribing to an RSS feed.

- [x] Investigate how to add the RSS feed to Jekyll.

- [x] Install the plugin
- [x] Test locally. __Result:__ It doe snot work with custom collections.

- [ ] Time for Keithy to develop yet another Jekyll Plugin. I'll be quick this time.

- [ ] Deploy to Netlify and test

- [ ] Add a link somewhere.

**Comment by keithmifsud** [comment]
I'll take this one.

**Comment by danielepolencic** [comment]
We have RSS now
