### ISSUE TITLE
Document how to add images to blog posts.

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#31]
Hi @danielepolencic ,

I'm trying to add an image to a blog post but cannot get it to work. I first copied your image tag from the "smaller images" post and updated the link but I cannot understand how the "link_blog" tag works. Can you please document this in Readme.

Thanks.

**Comment by danielepolencic** [comment]
Is there a PR where I can check the code?

**Comment by keithmifsud** [comment]
Not yet...just a final review of the post and I'll submit it for your review. I don't want to include the image as atm it is breaking the build.

How would you add an image to a post? Your post has this:

```
<!-- ![Smaller Docker images]({% link _blog/smaller-docker-images/smaller_images.png %}) -->
```

so I created an image in `_blog/deploying-laravel-to-kubernetes` named `laravel-and-kubernetes.png`, then added this link to the post:

```<!-- ![Deploying Laravel to Kubernetes]({% link _blog/smaller-docker-images/laravel-and-kubernetes.png %}) -->
```

For some reason, it seems that the build does not copy the image to the _site.

**Comment by keithmifsud** [comment]
@danielepolencic sorry...it's working now. For some reason, it got confused when I added your link first. It wasn't noticing that I have changed the image name until I stopped docker and restarted it. Maybe it's because of the delays I have with the Docker in VM.

**Comment by keithmifsud** [comment]
I used the image front-matter property for the image. I didn't notice that your one was commented out...thought it was a some sort of shortcode you've developed in liquid :)

**Comment by danielepolencic** [comment]
I forgot I should delete that comment too lol.
