### ISSUE TITLE
Add Social Media Share Links to articles.

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#49]
@danielepolencic I use [ShareThis](https://www.sharethis.com/) for my social share buttons on my site. Would you like the use this too?

I have [one post](https://keith-mifsud.me/the-fearless-natural-approach-to-tdd) with the share buttons at the very start of the content and at the end of the article's content. I found this to be a lot better than just at the bottom. What would you like both or just at the end?

Do you have any text in mind? Mine says _Don't be selfish..._

I can set this up and send you the credentials over Keybase. If you decide to use the same service, you can choose whether to show the number of shares or not. Please let me know your choice.

**Comment by danielepolencic** [comment]
Proposal:

I'd like to have sharing links next to the blog post like in Medium:

![kapture 2018-03-14 at 21 46 50](https://user-images.githubusercontent.com/1130499/37432731-4bd35d50-27d1-11e8-8c02-744bd5bc19f7.gif)

The links should look like this:

![image](https://user-images.githubusercontent.com/1130499/37432757-682147ce-27d1-11e8-9455-e6d68c3cd447.png)

And we should have the following services:

- Facebook
- Twitter
- G+
- LinkedIn
- Email

Ideally, we wouldn't use any JS to render the buttons. My advice would be to use something like this https://simplesharebuttons.com/html-share-buttons/

The buttons should be SVGs. Please find attached some demo SVGs [svgs.zip](https://github.com/learnk8s/learnk8s.io/files/1813253/svgs.zip)

The SVG should be optimised with something like https://jakearchibald.github.io/svgomg/

What do you think?

**Comment by keithmifsud** [comment]
@danielepolencic I'll try this out now. I will have some JS for animation purposes but this will be on the server.

**Comment by keithmifsud** [comment]
__Keith's__ 🤔 
- [ ] Setup an aside container with a fixed position.
- [ ] Add unordered list and remove styling.
- [ ] Add links to buttons (no imagery for quick testing).
- [ ] Optimise the SVG images.
- [ ] Test for medium and large screen devices.
- [ ] Add animation so that the container only shows after a certain scroll position. (preferably only CSS, no JS)
- [ ] Hide container for SM and XS screens.
- [ ] Create bottom container visible only to SM & XS screens.
- [ ] Add a fade-in transition.
- [ ] Test on several phone models.
