### ISSUE TITLE
Author Blurb Text Link Spans Out to Article Width

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#52]
Should have fixed width.

**Comment by danielepolencic** [comment]
In the team page?

**Comment by keithmifsud** [comment]
Nope, the blurb at the top of any article. I'll fix it myself since I built it wrong 😄 Look at the cursor / tooltip on the right of the author's avatar.
![image](https://user-images.githubusercontent.com/2071560/37822190-b0e04264-2e7d-11e8-9966-d13c28cd9b9a.png)

**Comment by danielepolencic** [comment]
Oh, I see!
