### ISSUE TITLE
Social Media Sharing Bugs and Enhancements

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#60]
- [x] Change the Twitter Sharing method to use the new Web Intent.
- [x] Consolidate the JS functions that handle the popup window.
- [x] Change the display of the sharing buttons for mobile devices so that they are static at the end of the article's content. - Moved to a new issue to avoid delays #GH-68

**Comment by danielepolencic** [comment]
About 90% of the shares comes Twitter. I'd really like to fix this, what can we do?

**Comment by keithmifsud** [comment]
I'll find a way to update the share window so that it displays the text and image preview before tweeting. On it, as we speak.

**Comment by keithmifsud** [comment]
@danielepolencic As it is, when tweeting, the tweet appears like this: 

![image](https://user-images.githubusercontent.com/2071560/39119026-c3100b86-46e2-11e8-9ff7-554082f6b249.png)

Just to make sure we're both on the same issue. Currently, once clicking on the twitter share link, a small window opens like this:
![image](https://user-images.githubusercontent.com/2071560/39119105-f51b406e-46e2-11e8-9b63-bf8101262cde.png)

Am I right to say that you want it to look like this?
![image](https://user-images.githubusercontent.com/2071560/39119176-1ea0b176-46e3-11e8-8028-6942f68295d3.png)

If so, Twitter is a bit different (obviously) because of the characters limit and the ability to have hash tags and a twitter username. I assume that we want the @learnk8s as the username?  Do you wnat to have automated hashtags generated? If so how should I get these? Add a front-matter property on each article?

**Comment by danielepolencic** [comment]
I think it would be nice if we could customise the message and tag @learnk8s

**Comment by keithmifsud** [comment]
Okay. I can limit the length using a liquid filter because the new "Web Intent" from Twitter's docs say that if the length is exceeded it won't be automatically cropped out and (although not clear) I assume that the text will simply not be included. Bear in mind that the URL text is included in the limit as it is displayed as part of the tweet.

**Comment by danielepolencic** [comment]
I think that should be fine for a first release.
