### ISSUE TITLE
Blog list will not show more than 5 posts and a link to an archive is not present.

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#92]
This needs to fixed before publishing the next 2 articles as of today the 12th June 2018.

- [x] create an additional dummy post for testing.

- [x] Issue exists due to `post_limit` in `_config` file?

- [x] Plan according to the above:
  - [ ] Install Jekyll-paginate-v2.
  - [ ] Configure the plugin.
  - [ ] Test it works as expected.
  - [ ] Add default front-matter setting so that all posts are automatically paginated and test.
  - [ ] Apply any required designs such as buttons' styling etc.

- [ ] Remove dummy post.

- [ ] Create PR and assign to a reviewer.

- [ ] Get PR merged and close.

**Comment by keithmifsud** [comment]
@danielepolencic The only available Jekyll plugin that handles pagination (Jekyll >3.0) does not work very well with custom collections. I don't mind to develop one and Open Source it because I'll use myself and the entire Jekyll community needs it. However, I wanted to make sure that this is what you're after. I.e. that each blog list page contains up to 5 posts and the rest split into numbered pages. Right?

**Comment by danielepolencic** [comment]
NA. We don't use Jekyll anymore.
