### ISSUE TITLE
Develop and Design the User Picks in newsletter layout and the latest contributors in the newsletter landing page.

### ISSUE THREAD

**Issue by keithmifsud** [learnk8s/learnk8s.io#95]
When we have user contributions to the newsletter, the user_pick section should be design and the newsletter landing page should be refactored/tested.

__Contributors:__

An include showing up to three contributors, including a profile photo and links to GH, Twitter, website and LinkedIn if and what is available. My opinion is that precedence should be given to contributors which are not team members at LearnK8s and team members should only be shown while there are less than 3 third-party contributors. Third party contributors are community members that have submitted links to a newsletter issue (in the "Your Picks" section).

In the newsletter landing page there should be a condition stating that if contributors are specified in the front-matter then the `_includes/newsletter/contributors/static.html` should be included, otherwise, the ``_includes/newsletter/contributors/latest.html` will be included as per specs above.

- [ ] Develop an `include` as per above specs.
- [ ] Ability to override which contributors to display in the front-matter.

```html
<!--

  first, loop through all the issues until we make up three contributors that have at least their full name and their avatar.

  if there's not enough contributors, then they can be manually set in frotn matter. The contributors in front matter will take precedence over the latest ones.


-->

{% assign contributors_number = 0 %}
{% assign contributors = "" %}

{% for issue in site.newsletter %}
  {% if contributors_number < 3 %}
    {% if issue.user_pick %}
      {% for pick in issue.user_pick %}
        {% if pick.user_full_name && pick.user_avatar %}
          {% if contributors_number > 0 %}
          {% assign contributors = contributors | append: ',' }} %}
          {% endif %}
          {% assign contributors = contributors | append: issue.issue | append: "-" | append: forloop.index %}
          {% assign contributors_number = contributors_number | | plus: 1 %}
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endif %}
{% endfor %}

{{ contributors }}
```

**Comment by danielepolencic** [comment]
Removed contributors. This isn't relevant anymore.
